default['hbase']['tar'] = "hbase-1.2.2-bin.tar.gz"
default['hbase']['url'] = "http://apache.is.co.za/hbase/stable/hbase-1.2.2-bin.tar.gz"
default['hadoop']['tar'] = "hadoop-2.7.2.tar.gz"
default['hadoop']['url']="http://apache.saix.net/hadoop/common/hadoop-2.7.2/hadoop-2.7.2.tar.gz"
default['hbase']['user']="vagrant"
